### ISSUE TITLE
This is awesome  planning to contribute to the code

### ISSUE THREAD

**Issue by rturk** [relax/relate#13]
Hi @bruno12mota @bs1180 @s-coimbra21 @joaosamouco this code is amazing. I'm planning to contribute to the code and test it in my App.

**Comment by rturk** [comment]
Any plans to create a Gitter or Slack channel to discuss best practices, share code, ideas?

**Comment by bruno12mota** [comment]
Hey @rturk. This project is being used on [Relax](https://github.com/relax/relax), there's a channel o relax's slack for relate if you want to discuss something with us. The work needed right now is around unit testing since the tests coverage is not ideal, so if you want to contribute that would be a good place to start 😄
